language: python
cache: pip
python:
  - "3.7"
dist: xenial
install:
  - pip install pipenv
  - pipenv install --system --deploy --ignore-pipfile
  - pip install codecov
script:
  - mypy
  - pytest --cov-report term
  - flake8
after_success:
  - codecov