language: python
cache: pip
python:
  - "3.7"
dist: xenial
install:
  - pip install pipenv
  - pipenv install --system --dev
  - pip install codecov
script:
  - mypy
  - pytest --cov-report=xml --cov
  - flake8
after_success:
  - codecov
