language: python
python:
  - "3.7"
dist: xenial
install:
  - pip install pipenv
  - pipenv install --dev
  - pipenv shell pip install codecov
script:
  - pipenv run mypy
  - pipenv run pytest --cov-report term
  - pipenv run flake8
after_success:
  - codecov